### ISSUE TITLE
Not sure, I think there is problem of local data adblock

### ISSUE THREAD

**Issue by leandroong** [jedisct1/unbound#3]
unless I change the DNS to 8.8.8.8, other than router ip, browser has problem completion display of site filehippo.com on iphone OS version 8.4.1. 
Note: to be precise, try clicking "LATEST updates" command button on that page

Also this problem only exhibit on iphone and not on android or windows

**Comment by jedisct1** [comment]
I don't think it has anything to do with Unbound...
