### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by leandroong** [jedisct1/unbound#5]
compiled on commit made on feb 19,2016 still not running
/opt/home/admin # unbound -v
[1455965500] unbound[9751:0] notice: Start of unbound 1.5.8.
Segmentation fault
/opt/home/admin #

**Comment by leandroong** [comment]
commit feb 23, 2016
/opt/home/admin # unbound -v
[1456331372] unbound[28409:0] notice: Start of unbound 1.5.8.
Segmentation fault
/opt/home/admin #

**Comment by leandroong** [comment]
commit Feb 24, 2016
/opt/home/admin # unbound -v
[1456336813] unbound[28821:0] notice: Start of unbound 1.5.8.
Segmentation fault
/opt/home/admin #

**Comment by jedisct1** [comment]
Unfortunately, "Segmentation fault" is not enough to have a clue about what is wrong.
Would you mind sharing a stack trace instead?

**Comment by leandroong** [comment]
I have no knowledge on stack trace.

**Comment by leandroong** [comment]
If only there is tag version, we can eliminate the issue. Currently using unbound version 1.5.8, file created on 12/2/15. 
Is there a way to roll back, so I can see what commit failed?

**Comment by jedisct1** [comment]
Sure, you can use `git checkout <commit id>` to switch the current view to any commit ID.

**Comment by leandroong** [comment]
Ok, after exhaustive compilation, error start on commit dated Jan 26, 2016.
Currently running Jan 25, 2016 compiled version.

**Comment by leandroong** [comment]
commit made on march 3, 2016
fixed segmentation issue. Tnx.
